# Generated by Django 5.2 on 2025-04-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='quiz_type',
            field=models.CharField(default='default_quiz_type', max_length=255),
        ),
    ]
