# Generated by Django 5.2 on 2025-04-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsystem',
            name='account',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='adminsystem',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
