# Generated by Django 5.2 on 2025-04-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSystem',
        ),
    ]
