# Generated by Django 5.2 on 2025-05-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_adminsystem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banneduserhistory',
            table='BannedUserHistory',
        ),
        migrations.AlterModelTable(
            name='chatbothistory',
            table='ChatbotHistory',
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='ChatMessage',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='consultantschedule',
            table='ConsultantSchedule',
        ),
        migrations.AlterModelTable(
            name='consultation',
            table='Consultation',
        ),
        migrations.AlterModelTable(
            name='expertinformation',
            table='ExpertInformation',
        ),
        migrations.AlterModelTable(
            name='expertwithdrawinformation',
            table='ExpertWithdrawInformation',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='Feedback',
        ),
        migrations.AlterModelTable(
            name='forumcontentmanagement',
            table='ForumContentManagement',
        ),
        migrations.AlterModelTable(
            name='forumpost',
            table='ForumPost',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='Notification',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='Quiz',
        ),
        migrations.AlterModelTable(
            name='quizresult',
            table='QuizResult',
        ),
        migrations.AlterModelTable(
            name='report',
            table='Report',
        ),
        migrations.AlterModelTable(
            name='revenuemanagement',
            table='RevenueManagement',
        ),
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='Transaction',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
        migrations.AlterModelTable(
            name='userinformation',
            table='UserInformation',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='UserRole',
        ),
    ]
