# Generated by Django 5.2 on 2025-04-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
