# Generated by Django 5.2 on 2025-04-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatmessage_delete_chatsystemhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
