# Generated by Django 5.2 on 2025-05-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_expertinformation_account_balance_transaction_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneduserhistory',
            name='reject_count',
            field=models.IntegerField(default=0),
        ),
    ]
