# Generated by Django 5.2 on 2025-04-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbothistory',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
