# Generated by Django 5.2 on 2025-04-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chatbothistory_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbothistory',
            name='conversation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
