from django.contrib import admin
from .models import *

admin.site.register(User)
admin.site.register(Role)
admin.site.register(UserRole)
admin.site.register(QuizResult)
admin.site.register(UserAnswer)
admin.site.register(ChatbotHistory)
admin.site.register(ChatSystemHistory)
admin.site.register(Notification)
admin.site.register(ForumPost)
admin.site.register(Comment)
admin.site.register(Report)
admin.site.register(BannedUserHistory)
admin.site.register(Transaction)
admin.site.register(RevenueManagement)
admin.site.register(ExpertInformation)
admin.site.register(ConsultantSchedule)
admin.site.register(Consultation)
admin.site.register(ExpertWithdrawInformation)
admin.site.register(Feedback)
admin.site.register(UserInformation)
admin.site.register(ForumContentManagement)
